### ISSUE TITLE
部署有问题

### ISSUE THREAD

**Issue by shonve** [b3log/xiaov#11]
[org.b3log.xiaov.XiaoVServletListener:90]: Destroyed the context，这个包有问题么？

**Comment by 88250** [comment]
麻烦贴一下完整的日志 :-p

**Comment by shonve** [comment]
`25-Jul-2016 19:30:40.752 INFO [main] org.apache.catalina.core.AprLifecycleListener.init Loaded APR based Apache Tomcat Native library 1.1.31 using APR version 1.4.8.
25-Jul-2016 19:30:40.752 INFO [main] org.apache.catalina.core.AprLifecycleListener.init APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
25-Jul-2016 19:30:42.019 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized (OpenSSL 1.0.1h 5 Jun 2014)
25-Jul-2016 19:30:42.207 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-apr-8080"]
25-Jul-2016 19:30:42.222 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-apr-8009"]
25-Jul-2016 19:30:42.222 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 2121 ms
25-Jul-2016 19:30:42.316 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
25-Jul-2016 19:30:42.316 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.12
25-Jul-2016 19:30:42.347 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-apr-8080"]
25-Jul-2016 19:30:42.363 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-apr-8009"]
25-Jul-2016 19:30:42.379 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 160 ms
Connected to server
[2016-07-25 07:30:42,832] Artifact xiaov:war exploded: Artifact is being deployed, please wait...
25-Jul-2016 19:30:44.879 INFO [RMI TCP Connection(3)-127.0.0.1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
[INFO ]-[2016-07-25 19:30:45]-[org.b3log.xiaov.service.QQService:193]: 开始初始化小薇
25-Jul-2016 19:30:45.634 SEVERE [RMI TCP Connection(3)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal Error listenerStart
25-Jul-2016 19:30:45.634 SEVERE [RMI TCP Connection(3)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
[INFO ]-[2016-07-25 19:30:45]-[org.b3log.xiaov.XiaoVServletListener:90]: Destroyed the context
25-Jul-2016 19:30:45.650 SEVERE [RMI TCP Connection(3)-127.0.0.1] org.apache.catalina.loader.WebappClassLoader.checkThreadLocalMapForLeaks The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@32edb0e]) and a value of type [org.b3log.latke.util.Stopwatchs.Stopwatch] (value [[100]%, [-1469446245087]ms [Context Initialized]
]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
[2016-07-25 07:30:45,681] Artifact xiaov:war exploded: Error during artifact deployment. See server log for details.
25-Jul-2016 19:30:52.381 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory E:\tool\apache-tomcat-8.0.12\webapps\manager
25-Jul-2016 19:30:52.490 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory E:\tool\apache-tomcat-8.0.12\webapps\manager has finished in 109 ms
`

**Comment by 88250** [comment]
我没有在 Tomcat 里面部署过。你在 web.xml 里面删除掉这个再试试：

```xml
<servlet>
    <servlet-name>default</servlet-name>
    <servlet-class>org.eclipse.jetty.servlet.DefaultServlet</servlet-class>
    <init-param>
        <param-name>useFileMappedBuffer</param-name>
        <param-value>false</param-value>
    </init-param>
</servlet>
```

**Comment by shonve** [comment]
跟这个好像没关系，我试了还是一样的。我是因为jetty启动过程中要下载大量文件，太慢了，而且也没用过那个，不怎么熟，所以才试着tomcat启动的。

**Comment by 88250** [comment]
好的，等有空我试下用 Tomcat 启动，如果解决了的话我会关闭这个 issue 的，先多谢你的反馈啦！

**Comment by 88250** [comment]
刚刚我测试了一下，部署到 Tomcat 9.0.0.M3 和 Tomcat 8.0.12 都可以正常启动的。你打包的过程是用 maven install 么？

**Comment by shonve** [comment]
不好意思，家里面可以运行起来，公司的不行，可能公司环境的问题，谢谢你啦，辛苦了

**Comment by 88250** [comment]
没事 :smile: 

我关闭这个 issue 了。
