### ISSUE TITLE
部署疑问ERROR

### ISSUE THREAD

**Issue by nEdAy** [b3log/xiaov#13]
只让我扫了机器人Q的码 没有守护
扫码后ERROR
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building XiaoV 1.0.1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> jetty-maven-plugin:9.2.7.v20150116:run (default-cli) > test-compile @ xiaov >>>
[WARNING] The POM for other.third:dependencies:jar:1.0.0 is missing, no dependency information available
[INFO]
[INFO] --- maven-license-plugin:1.9.0:format (default) @ xiaov ---
[INFO] Updating license headers...
[INFO]
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ xiaov ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 7 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ xiaov ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ xiaov ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory Z:\Users\nEdAy\Desktop\xiaov-master\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ xiaov ---
[INFO] No sources to compile
[INFO]
[INFO] <<< jetty-maven-plugin:9.2.7.v20150116:run (default-cli) < test-compile @ xiaov <<<
[INFO]
[INFO] --- jetty-maven-plugin:9.2.7.v20150116:run (default-cli) @ xiaov ---
[INFO] Logging initialized @2175ms
[INFO] Configuring Jetty for project: XiaoV
[INFO] webAppSourceDirectory not set. Trying src\main\webapp
[INFO] Reload Mechanic: automatic
[INFO] Classes = Z:\Users\nEdAy\Desktop\xiaov-master\target\classes
[INFO] Context path = /
[INFO] Tmp directory = Z:\Users\nEdAy\Desktop\xiaov-master\target\tmp
[INFO] Web defaults = org/eclipse/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
[INFO] web.xml file = file:/Z:/Users/nEdAy/Desktop/xiaov-master/src/main/webapp/WEB-INF/web.xml
[INFO] Webapp directory = Z:\Users\nEdAy\Desktop\xiaov-master\src\main\webapp
[INFO] jetty-9.2.7.v20150116
[INFO ]-[2016-07-26 00:53:50]-[org.b3log.xiaov.service.QQService:193]: 开始初始化小薇
[INFO ]-[2016-07-26 00:53:51]-[com.scienjus.smartqq.client.SmartQQClient:105]: 二维码已保存在 Z:\Users\nEdAy\Desktop\xiaov-master\qrcode.png 文件中，请打开手机QQ并扫描二维码
[INFO ]-[2016-07-26 00:54:17]-[com.scienjus.smartqq.client.SmartQQClient:120]: 正在登录，请稍后
[INFO ]-[2016-07-26 00:54:18]-[org.b3log.xiaov.service.QQService:686]: Reloaded groups:
    xxxx|测试|: 377376xxxx

[INFO ]-[2016-07-26 00:54:18]-[org.b3log.xiaov.service.QQService:703]: Reloaded discusses:

[INFO ]-[2016-07-26 00:54:18]-[org.b3log.xiaov.service.QQService:260]: 小薇初始化完毕
[INFO ]-[2016-07-26 00:54:18]-[org.b3log.xiaov.service.QQService:309]: 小薇 QQ 机器人服务开始工作！
[INFO ]-[2016-07-26 00:54:18]-[org.b3log.xiaov.XiaoVServletListener:72]: Initialized the context
[INFO] Started o.e.j.m.p.JettyWebAppContext@562457e1{/,file:/Z:/Users/nEdAy/Desktop/xiaov-master/src/main/webapp/,AVAILABLE}{file:/Z:/Users/nEdAy/Desktop/xiaov-master/src/main/webapp/}
[WARNING] !RequestLog
[INFO] Started ServerConnector@338b49d3{HTTP/1.1}{0.0.0.0:9090}
[INFO] Started @31111ms
[INFO] Started Jetty Server
[ERROR]-[2016-07-26 00:54:28]-[com.scienjus.smartqq.client.SmartQQClient:72]: java.net.SocketTimeoutException: Read timed out
[ERROR]-[2016-07-26 00:54:38]-[com.scienjus.smartqq.client.SmartQQClient:72]: java.net.SocketTimeoutException: Read timed out

**Comment by 88250** [comment]
默认不启用守护，如果需要请参考配置项。
