### ISSUE TITLE
调用接口群发问题

### ISSUE THREAD

**Issue by red3** [b3log/xiaov#17]
终端：Mac
请求日志如下：

~ » curl -X POST -F 'key=123456' -F 'msg=hhhhhhkkljljjl' http://0.0.0.0:9090/qq
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 403 Forbidden</title>
</head>
<body><h2>HTTP ERROR 403</h2>
<p>Problem accessing /qq. Reason:
<pre>    Forbidden</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>

**Comment by red3** [comment]
另外，往 讨论组 发送消息应该用哪个 api 呢？readme中没有看到。感谢回复以及开发了这个项目。

**Comment by red3** [comment]
奇怪的是我用 postman 发送的请求，server是接受到的，可以看到log：

[WARN ]-[2016-07-28 17:35:16]-[org.b3log.xiaov.processor.QQProcessor:84]: hhhhhhkkljljjl

但是请求报 400. 消息最终也是没有发送到群里。

**Comment by 88250** [comment]
你要完成什么功能，麻烦说一下场景。

**Comment by red3** [comment]
我用 curl 只是想测试下 server 是否部署成功。
我想完成的功能是在 ruby 脚本中调用小薇向 qq群推送消息。所以我首先用 curl 模拟了一次调用小薇的接口。结果是报 403.

**Comment by red3** [comment]
我把接口按这个方式 `/qq?key=123456&msg=helloworld` 请求后，控制台看到是可以接受到接口发出的消息了
这是控制台的输出：
```
[WARN ]-[2016-07-29 09:34:19]-[org.b3log.xiaov.processor.QQProcessor:84]: helloworld
```
但是群里面并没有收到消息。

server 初始化的时候是拉取到群消息的，如下：

```
[INFO ]-[2016-07-29 09:24:43]-[com.scienjus.smartqq.client.SmartQQClient:120]: 正在登录，请稍后
[INFO ]-[2016-07-29 09:24:48]-[org.b3log.xiaov.service.QQService:688]: Reloaded groups:
    重温经典: 3653159178

[INFO ]-[2016-07-29 09:24:48]-[org.b3log.xiaov.service.QQService:705]: Reloaded discusses:
    测试: 3074534343
```

配置文件里面配置的是向所有的群推送消息的
```
qq.bot.key=123456
qq.bot.pushGroups=*
```

**Comment by red3** [comment]
看来是下面的代码的原因了, msg 里面必须含有论坛的地址。

```
 if (StringUtils.contains(msg, "http://localhost") || !StringUtils.contains(msg, "https://hacpai.com")) {
            LOGGER.warn(msg);
            response.sendError(HttpServletResponse.SC_BAD_REQUEST);

            return;
        }
```

**Comment by 88250** [comment]
配置应该是对的，你先加完群再发送群推看看。

**Comment by 88250** [comment]
哦，嗯，这个地方我写死了，你换一下吧。

**Comment by red3** [comment]
好的

**Comment by 88250** [comment]
多谢反馈啦

**Comment by red3** [comment]
源码 是 不接受论坛推送的，我尝试把下面的注释去掉后
```
 //qqService.sendToPushQQGroups(msg);

```
控制台打印如下日志：
```
[INFO ]-[2016-07-29 10:17:31]-[org.b3log.xiaov.processor.QQProcessor:101]: Push QQ groups [articleTitle=helloworld, articleLink=helloworld]
[INFO ]-[2016-07-29 10:17:31]-[org.b3log.xiaov.service.QQService:413]: 一共推送了 [0] 个群，覆盖 [0] 个 QQ
```
难道是 qqService 需要初始化的缘故？我不太懂 Java了。

**Comment by red3** [comment]
莫非是这个原因，我的群里面才3个人，都是测试号😢
```
 /**
     * 超过 {@value #PUSH_GROUP_USER_COUNT} 个成员的群才推送.
     */
    private static final int PUSH_GROUP_USER_COUNT = 50;
```

**Comment by red3** [comment]
果然是这个原因了，改成 PUSH_GROUP_USER_COUNT = 2 就可以成功推送了

**Comment by 88250** [comment]
好的，我记下了，后续会把这个改在配置里面，再次感谢了~
