### ISSUE TITLE
希望考虑支持终端输出登录二维码

### ISSUE THREAD

**Issue by red3** [b3log/xiaov#18]
为了操作的连贯性，以及考虑到有些终端机器并不含有 UI 界面。

**Comment by 88250** [comment]
弄个下载二维码的接口么？

**Comment by red3** [comment]
我感觉可以直接在终端log出二维码的，用白色和黑色的色块。
查到了一个参考，你看看：http://leo108.com/pid-2161.asp

**Comment by 88250** [comment]
这也行，我研究一下 :-)

**Comment by 88250** [comment]
#22 中提到的方式更好一些，所以我关闭这个 issue 了，多谢你的思路~
