### ISSUE TITLE
一直刷SocketTimeout

### ISSUE THREAD

**Issue by juzeon** [b3log/xiaov#21]
![2016-08-11 2 52 49](https://cloud.githubusercontent.com/assets/12206799/17580753/873c36ae-5fd3-11e6-9896-35dbec6e3d5d.png)
可以帮忙解决一下吗？

**Comment by 88250** [comment]
你看下功能有没有问题，如果没有问题就先忽略这个异常吧。

**Comment by lexburner** [comment]
[com.scienjus.smartqq.client.SmartQQClient:76]: java.net.SocketTimeoutException: Read timed out 我也遇到这个问题，之前用的好好的

**Comment by 88250** [comment]
最新版本应该解决了。
