### ISSUE TITLE
二维码的另一种打开方式

### ISSUE THREAD

**Issue by abinnz** [b3log/xiaov#22]
在服务器上通常无法像windows系统一样，方便性查看二维码图片，往往只能查看应用运行日志。因此，巧借https://sm.ms/doc/ 接口，将二维码上传，打开API返回的网址就可以查看二维码，延续机器人登陆操作。另外， 我想出个教程关于部署机器人到heroku。

**Comment by 88250** [comment]
1. 因为小薇自身就是个 Web 服务，所以理论上是可以通过自己的 HTTP 服务直接打开服务器上的图片文件的，稍后我会修改一下代码，以支持这个特性，多谢你提供的这个思路~
2. 欢迎出教程，可以放到[论坛里面](https://hacpai.com/tag/%E5%B0%8F%E8%96%87)，然后我会在项目主页中进行索引
