### ISSUE TITLE
消息发送成功状态码错误

### ISSUE THREAD

**Issue by notreami** [b3log/xiaov#27]
![image](https://cloud.githubusercontent.com/assets/10699639/23447976/5c6997c8-fe89-11e6-9fab-dfd7483d13df.png)
![image](https://cloud.githubusercontent.com/assets/10699639/23447978/644ed3a4-fe89-11e6-862f-35c73f4bd7ed.png)
![image](https://cloud.githubusercontent.com/assets/10699639/23448024/9b427618-fe89-11e6-8932-ac5536f4a4b3.png)

在讨论组里，发送成功的状态码是100100

**Comment by 646222123** [comment]
同上 我的也是这样 @88250 大大 这是什么问题

**Comment by 88250** [comment]
@646222123 那个状态码不一定对。

**Comment by 646222123** [comment]
明白了  我已经找到了  并加入了自己的逻辑   谢谢  大大及时解答



sunyigao@foxmail.com
 
发件人： D
发送时间： 2017-03-02 14:15
收件人： b3log/xiaov
抄送： 646222123; Mention
主题： Re: [b3log/xiaov] 消息发送成功状态码错误 (#27)
@646222123 那个状态码不一定对。
