### ISSUE TITLE
推送消息的接口不可用吧

### ISSUE THREAD

**Issue by iminto** [b3log/xiaov#29]
http://127.0.0.1:8080/qq?key=123456&msg=%E7%8B%97run  POST无效
http://127.0.0.1:8080/favicon.png 这个是可以访问到的。
证明了8080端口是好的，但是  /qq 这个地址没法访问

文档写的莫名其妙啊

**Comment by 88250** [comment]
应该可以用，我好久没试了，有空看看。

**Comment by 88250** [comment]
还需要解决么？我先关闭了。
