### ISSUE TITLE
推送消息到Q群的api使用问题

### ISSUE THREAD

**Issue by youyinnn** [b3log/xiaov#31]
大神你好 我是第一次接触jetty 其中的一些细节不太懂
我在本地部署好小薇之后 怎么写一个html页面发送post请求让我的机器人在群里发消息呢？

功能：小薇提供给论坛调用的 HTTP 接口，用于将论坛的内容推送到 QQ 群
URL：/qq
Method：POST
Body：key={qq.bot.key}&msg={msgcontent}
例如：/qq?key=123456&msg=Hello

这个路径始终找不到

我的from是这样写的:

    <form action="/qq" method = "post">
        key:<input type="text" name="key" value="123456"/>
        <br><br>
        message&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:<input type="text"  name="message" value="Hello"/>
        <br><br>
        <input class="login" type="submit" value="send">
    </form>

**Comment by 88250** [comment]
建议先用 HTTP 调试工具（比如 Postman）调通再进行页面集成。
