### ISSUE TITLE
SmartQQClient.getQQById("xxxx") 请求失败，Http返回码[404]

### ISSUE THREAD

**Issue by 1123311314** [b3log/xiaov#32]
通过  client.getQQById(message) 获取发送信息的QQ号是，返回错误吗是 404 ， 不清楚是为什么，我尝试过 onMessage、onGroupMessage 都是一样的，希望能帮忙一起看一下，是不是
com.scienjus.smartqq.constant.ApiURL.GET_QQ_BY_ID 的URL有问题

**Comment by 88250** [comment]
请到 https://github.com/ScienJus/smartqq/issues/new 反馈。

**Comment by shiyafeng** [comment]
smartqq腾讯已经不维护了 你可以试试另一种稳定的方式 https://github.com/shiyafeng/foolqq

**Comment by 1123311314** [comment]
/foolqq/src/main/java/foolqq/BaseQQWindowContext.java line:78
此处从map获取 Logo图片位置 x,y ，循环：	for (int i = x - 100; i < x + 200; ++i)  为啥要减去100个像素， 如果窗口x太靠近边缘，导致 x为负数了，之后 QQWindowTool.isEqual() 会报错，然后程序就假死了。

**Comment by 1123311314** [comment]
从设计上来看，不清楚作者将如何来实现指定QQ发送消息等其他功能

发送自 Windows 10 版邮件应用

发件人: dyj_tian@yeah.net
发送时间: 2017年10月31日 11:57
收件人: b3log/xiaov
主题: 图像处理操作QQ的工具foolqq 问题请教


/foolqq/src/main/java/foolqq/BaseQQWindowContext.java line:78
此处从map获取 Logo图片位置 x,y ，循环：  for (int i = x - 100; i < x + 200; ++i)  为啥要减去100个像素， 如果窗口x太靠近边缘，导致 x为负数了，之后 QQWindowTool.isEqual() 会报错，然后程序就假死了。
