### ISSUE TITLE
小薇 @小薇   和 直接发  小薇

### ISSUE THREAD

**Issue by ydcun** [b3log/xiaov#4]
一直@小薇 的时候它一直认为我发的是统一，让我换个问题 我直接小薇 的是就没问题

**Comment by 88250** [comment]
收到，等有空解决。

**Comment by 88250** [comment]
已经解决了，欢迎帮忙测试。

**Comment by ydcun** [comment]
[`看图片就清楚了`](https://github.com/ydcun/ydcun.github.io/blob/master/img/QQ%E6%88%AA%E5%9B%BE20160623151259.jpg)

**Comment by 88250** [comment]
@ydcun 
程序上两种都会响应的。最近不响应主要是因为小薇的Q账号被人举报太多，导致账号异常了....
