### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by MMDKZT** [b3log/xiaov#44]
1.建议更新图灵的API，毕竟人家已经开放了 API 2.0
2.建议可以可选地尝试重新登陆上次登录的账号（利用Cookies）
3.能不能把  “嗯~”  这个去掉，每次都在回复后带一个这个东西。而且有时会自动发，即使没有打上“小薇”二字

**Comment by 88250** [comment]
谢谢建议，更新了第三点。
