### ISSUE TITLE
[ERROR]-[2016-06-27 21:45:35]-[org.b3log.xiaov.service.QQService:337]: Group list error [groupId=773768100], please report this bug to developer: https://github.com/b3log/xiaov/issues/new

### ISSUE THREAD

**Issue by sinnerliu** [b3log/xiaov#6]
[ERROR]-[2016-06-27 21:45:35]-[org.b3log.xiaov.service.QQService:337]: Group list error [groupId=773768100], please report this bug to developer: https://github.com/b3log/xiaov/issues/new

**Comment by 88250** [comment]
出现这个问题的话请先关闭小薇，然后 QQ 登录 w.qq.com，刷新页面后再设置里面退出 w.qq.com，最后再启动小薇。
